#!/usr/bin/env bash 

NAME="$1"
DOMAIN="$2"

# Fancy Complainer
usage() {
    local message=$(printf "\n\e[1;31m----[ERROR] Missing argument\e[0m\n")

    cat <<-EOF
    ${message}
    
    USAGE: domain-ping [USERNAME] [DOMAIN]

    Pings domain of choice and saves results
    to a file name USERNAME.log

EOF
    exit 1
}

# If not two parameters then complain
[[ -z "$1" || -z "$2" ]] && { usage; exit 1; } 

pinger() {
    echo "Username: $1" >> ping.log
    date >> ping.log
    ping -c 5 "${2}" | tee -a ping.log 
    printf -- "------- END --------\n\n" >> ping.log
}

pinger $NAME $DOMAIN
