#!/usr/bin/env bash
# 
# An animated spinner.
#
# Directly ported from Dave Eddy
# January 7, 2025
# Ryan Sibert

SPINNER_PID= # ensure pid is clear 
DEBUG=false


usage() {
    local prog=${0##*/}
    cat <<-EOF
    
    Usage: $prog [options] <cmd> 

    Run a command with a spinner.

    Options: 
       -d    enable debut output
       -h    print this message and exit

EOF
}

debug() {
    if $DEBUG; then
        echo "[$$] $*" >&2
    fi
}

# Spinner design
spinner() {
    local ticker=(
        #'......||'
        #'\.....||'
        #'\\....||'
        #'\\\...||'
        #'.\\\..||'
        #'..\\\.||'
        #'...\\\||'
        #'....\\||'
        #'.....\||'
        #'......||'
        #'...../||'
        #'....//||'
        #'...///||'
        #'..///.||'
        #'.///..||'
        #'///...||'
        #'//....||'
        #'/.....||'
        #'......||'

        '.........||'
        '*........||'
        '<*.......||'
        '.-*......||'
        '..<*.....||'
        '...-*....||'
        '....<*...||'
        '.....-*..||'
        '......<*.||'
        '.......-*||'
        '........<||'
        '.........||'
        '........*||'
        '.......*>||'
        '......*-.||'
        '.....*>..||'
        '....*-...||'
        '...*>....||'
        '..*-.....||'
        '.*>......||'
        '*-.......||'
        '>........||'
        '.........||'
        
        #'>....||'
        #'.>...||'
        #'..>..||'
        #'...>.||'
        #'....>||'
        #'....<||'
        #'...<.||'
        #'..<..||'
        #'.<...||'
        #'<....||'
    )

    local i
    while true; do
        for i in "${ticker[@]}"; do
            printf ' %s\r ' "$i"
            sleep .2
        done
    done
}

cleanup() {
    if [[ -n $SPINNER_PID ]]; then
        kill "$SPINNER_PID"
    fi
    debug "finished spinner"
}

main() {

    local opt OPTIND OPTARG
    while getopts 'dh' opt; do
        case "$opt" in 
            d) DEBUG=true;;
            h) usage; return 0;;
            *) usage >&2; return 1;;
        esac
    done

    # shift arguments and test for an argument
    shift "$((OPTIND - 1))"
    [[ $# == 0 ]] && { usage >&2; exit 1; }

    trap cleanup EXIT
    debug "Starting spinner."
    spinner & # starts the function in the background
    SPINNER_PID=$! # store the PID so we can kill it later

    debug "SPINNER_PID is $SPINNER_PID"

    "$@"
}

main "$@"
